algoritmo "desafio"
// Função :
// Autor : Gustavo Pimentel
// Data : 05/09/2022
// Seção de Declarações 
var
numero,linhas,colunas:inteiro

inicio
escreval("Digite um numero:")
leia(numero)

    para linhas de 1 ate numero faca
         para colunas de 1 ate linhas faca
              escreva(colunas)
         fimpara
         escreval()
    fimpara









// Seção de Comandos 
fimalgoritmo
