algoritmo "semnome"
// Função :
// Autor :
// Data : 19/09/2022
// Seção de Declarações 
var
contador,soma:inteiro
inicio

 para contador de 1 ate 20 faca
      se contador mod 2 = 0 entao
      escreval (contador)
      soma <- soma + contador
      fimse
 fimpara
 

H


//contador  <- 1
//enquanto  ((contador >=1) e (contador <=20)) faca
//         escreval(contador)
//         contador <- contador + 1
//fimenquanto







// Seção de Comandos 
fimalgoritmo
