algoritmo "semnome"
// Função :
// Autor :
// Data : 22/03/2022
// Seção de Declarações 
var
nome:caracter
idade:inteiro
salario:real
inicio

escreval("Digite seu Nome:  ")
leia(nome)

escreval("Digite sua idade:  ")
leia(idade)

escreval("Digite seu salario:  ")
leia(salario)


escreval("O seu nome é:  ",nome)
escreval("A sua idade é:  ",idade)
escreval("O seu salario é:  ",salario)

// Seção de Comandos 
fimalgoritmo
