algoritmo "ex 1 "
// Função :
// Autor : Gustavo Pimentel
// Data : 07/11/2022
// Seção de Declarações 
var
numeros: vetor [1..10] de inteiro
soma,contador:inteiro

inicio


para contador de 1 ate 10 faca
     numeros[contador] <- randi(10)
     escreva(numeros[contador])
     soma <- soma+(numeros[contador])
     
 fimpara
 escreval
 escreval("A soma dos numeros é: ",soma)




// Seção de Comandos 
fimalgoritmo
