algoritmo " EX 5 "
// Função :
// Autor : Gustavo Pimentel
// Data : 08/08/2022
// Seção de Declarações 
var

idade:inteiro
altura:real



inicio


escreval("digite sua idade")
leia(idade)
escreval("digite sua altura")
leia(altura)

se ((idade>=14) e (altura>=1.75)) entao
   escreval("Você pode competir")
senao
   escreval("Você nâo pode competir")


fimse



// Seção de Comandos 
fimalgoritmo
