algoritmo "semnome"
// Função : Fluxo Dollar
// Autor : Gustavo Pimentel
// Data : 02/05/2022
// Seção de Declarações 
var
cotacao:real
valor_reais:real
valor_dollar:real
inicio

escreval("Digite a cotação do dollar: ")
leia(cotacao)
escreval("Digite a quantia em reais, para conversão: ")
leia(valor_reais)


valor_dollar <- valor_reais/cotacao


escreval("O valor convertido equivale a US$:  ",valor_dollar)












// Seção de Comandos 
fimalgoritmo
