algoritmo "estoque medio"
// Função :
// Autor : Gustavo Pimentel
// Data : 02/05/2022
// Seção de Declarações 
var
qtdemin:real
qtdemax:real
estoquemedio:real

inicio
 escreval("Digite sua qtdemin:  ")
 leia(qtdemin)
 escreval("Digite sua qtdemax:  ")
 leia(qtdemax)

 estoquemedio <- (qtdemin+qtdemax)/2

  escreval("O seu estoque medio é:",estoquemedio)


// Seção de Comandos 
fimalgoritmo
