algoritmo "semnome"
// Função :
// Autor :
// Data : 19/09/2022
// Seção de Declarações 
var
contador,numfim,numinicio:inteiro
inicio

numfim<-400
numinicio<-90
para contador de numinicio ate numfim faca
     escreval(contador)
fimpara

numfim<-contador-1

escreval("o número inicial é: ",numinicio)
escreval("o número final é: ",numfim)




// Seção de Comandos 
fimalgoritmo
